### ISSUE TITLE
Strange result with patch submission and review

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#83]
I went through the BM collection and fixed some dates that were formatted in such a way that they couldn't be automatically parsed. When I was done, I submitted a patch, in which all the records looked basically like this:

![patch_presub](https://cloud.githubusercontent.com/assets/4740995/9453328/41a09bae-4a7f-11e5-9863-672a6ccbb146.JPG)

But after the patch had been successfully submitted and I went to review it, the same record looked like this:

![patch_postsub](https://cloud.githubusercontent.com/assets/4740995/9453342/55789348-4a7f-11e5-8bac-895f0fdc9e3a.JPG)

Any thoughts on why the stop date shows different (and problematic) edits, with the parenthetical value replaced with "not given" and the ISO date missing? I checked the record itself, and it doesn't show any problem with the stop date (nor is the parse dates automatically box checked). This happened to a number of the changed records, but not all, and I can't figure out what the ones affected have in common.

**Comment by ptgolden** [comment]
I think I found what was wrong, it should be fixed in version 2.3.5 (deployed now). Can you resubmit those changes and see if the resulting patch works as expected?

**Comment by ptgolden** [comment]
Actually, if you wouldn't mind holding off for a second, I'm going to make one more change

**Comment by atomrab** [comment]
Whoops, tried again before I got the last comment. It was still having the problem just now, but I'll pull back and wait for you to give the signal.

**Comment by ptgolden** [comment]
Really? Was your version 2.3.5? It should have been fixed there-- I was working on something else

**Comment by ptgolden** [comment]
This is annoying, but would you mind doing the following once I release 2.3.6:

  * Make a new backend
  * Sync the BM data
  * Re-do the changes you mentioned in your original comment (sorry about this, it's a one-time thing)
  * Resubmit the patch

Hopefully everything will be fixed.

**Comment by ptgolden** [comment]
ignore my last message, I don't think you'll even need to do all that... give me a minute

**Comment by ptgolden** [comment]
OK, can you try just resubmitting the patch (without doing any of the steps in my previous comment)

**Comment by atomrab** [comment]
Done (in 2.3.6). This one looks good. Let me know if I can go ahead and approve it.

**Comment by ptgolden** [comment]
Yep, seems like everything is fine. Marking this as fixed.
